################################# Default configuration ###################
# provide your domain here
baseURL = "https://brocktnl.github.io"
# theme
theme = "dot-hugo"
# site title
title = "Brock Library Digital Learning"
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)
# unsafe html
[markup.goldmark.renderer]
unsafe = true


############################# Default Parameters ##########################
[params]
# logo is for all page
logo = "images/brock-logo-black.svg"
# logo white is for homepage logo, you can use colorful logo too...
logo_white = "images/brock-logo-black.svg"
# when logo is empty, it will shown your site title

# OpenGraph / Twitter Card metadata
description = "Welcome to Brock Library Digital Learning."
author = "Brock Teaching and Learning"
image = "images/brock-library-logo.png" # this image will be used as fallback if a page has no image of its own

# customize color
primary_color = "#CC0000"
body_color = "#f9f9f9"
text_color = "#242738"
text_color_dark = "#242738"
text_color_contrast = "#ffffff"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "Source Sans Pro" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io


############################## social links ##############################

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
name = "Twitter"
link = "#"
  
[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
name = "Github"
link = "https://github.com/brockTnL/brocktnl.github.io"
  

################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
copyright = "Copyright © 2022 - . Site managed by Brock Library, eLearning Team. Site built using Hugo, with Dot theme by Themefisher."

# banner
[Languages.en.params.banner]
title = "What do you want to know?"
subtitle = "Find lessons, research tips, and advice from our librarian experts"
bg_image = ""

# call to action
[Languages.en.params.cta]
enable = true
title = "Didn't find an answer to your question?"
content = "Schedule a one-on-one research consultation with a librarian."
# call to action button
[Languages.en.params.cta.button]
enable = true
label = "book a research consultation"
link = "contact"


################## english navigation #################
[[Languages.en.menu.main]]
name = "Home"
url = "/"
weight = 1

[[Languages.en.menu.main]]
name = "About"
url = "faq"
weight = 2

[[Languages.en.menu.main]]
name = "Lessons"
url = "lessons"
weight = 3

[[Languages.en.menu.main]]
name = "Search"
url = "search"
weight = 4

[[Languages.en.menu.main]]
name = "Teaching Collection"
url = "teaching-collection"
weight = 5


################################### Franch Language ######################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
weight = 2
copyright = "Copyright © 2022 un thème Hugo par [Gethugothemes](https://gethugothemes.com/)"

# banner
[Languages.fr.params.banner]
title = "Comment pouvons nous aider?"
subtitle = "Trouvez rapidement des conseils et des réponses auprès de notre équipe d'assistance ou contactez-nous."
bg_image = "images/banner.jpg"
placeholder = "Avoir une question? Il suffit de demander ici ou de saisir les termes"

# call to action
[Languages.fr.params.cta]
enable = true
title = "Vous n'avez pas trouvé de réponse à votre question?"
content = "Contactez-nous pour plus de détails sur les services supplémentaires et la tarification du travail personnalisé"
# call to action button
[Languages.fr.params.cta.button]
enable = true
label = "Contactez nous"
link = "contact"


################## french navigation #################
[[Languages.fr.menu.main]]
name = "Accueil"
url = "/"
weight = 1

[[Languages.fr.menu.main]]
name = "Faq"
url = "faq"
weight = 2

[[Languages.fr.menu.main]]
name = "contact"
url = "contact"
weight = 3

# Dropdown menu
[[Languages.fr.menu.main]]
weight = 4
name = "docs"
hasChildren = true

  [[Languages.fr.menu.main]]
  parent = "docs"
  name = "Installation"
  url = "installation"
  weight = 1

  [[Languages.fr.menu.main]]
  parent = "docs"
  name = "Billing and Pricing"
  url = "billing-pricing"
  weight = 2

  [[Languages.fr.menu.main]]
  parent = "docs"
  name = "Features"
  url = "features"
  weight = 3